namespace matrix_dotnet;

using System.Text.Json.Serialization;
using Refit;

/// <summary>
/// The IMatrixApi interface represents API endpoints directly and its implementation gets generated by Refit.
/// </summary>
public interface IMatrixApi {
	public record ErrorResponse(string errcode, string error, bool? soft_logout = null);

	[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
	[JsonDerivedType(typeof(UserIdentifier), typeDiscriminator: "m.id.user")]
	[JsonDerivedType(typeof(PhoneIdentifier), typeDiscriminator: "m.id.phone")]
	[JsonDerivedType(typeof(ThirdpartyIdentifier), typeDiscriminator: "m.id.thirdparty")]
	public abstract record Identifier();
	public record UserIdentifier(string user) : Identifier();
	public record PhoneIdentifier(string country, string phone) : Identifier();
	public record ThirdpartyIdentifier(string medium, string address) : Identifier();

	/// <summary>The return value of the <see cref="Login"/> function.</summary>
	public record LoginResponse(
		string access_token,
		string device_id,
		int? expires_in_ms,
		// string? HomeServer, // DEPRECATED
		string? refresh_token,
		// object WellKnown, // NOT IMPLEMENTED
		string user_id
	);

	/// <summary><see cref="Login"/></summary>
	[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
	[JsonDerivedType(typeof(PasswordLoginRequest), typeDiscriminator: "m.login.password")]
	[JsonDerivedType(typeof(TokenLoginRequest), typeDiscriminator: "m.login.token")]
	public abstract record LoginRequest(
		string? initial_device_display_name = null,
		string? device_id = null,
		bool refresh_token = true
	);

	/// <summary><see cref="Login"/></summary>
	public record PasswordLoginRequest(
			Identifier identifier,
			string password,
			string? initial_device_display_name = null,
			string? device_id = null,
			bool refresh_token = true
	) : LoginRequest(initial_device_display_name, device_id, refresh_token);

	/// <summary><see cref="Login"/></summary>
	public record TokenLoginRequest(
			string token,
			string? initial_device_display_name = null,
			string? device_id = null,
			bool refresh_token = true
	) : LoginRequest(initial_device_display_name, device_id, refresh_token);

	/// <summary> Perform login to receive an access and an optional refresh token.
	/// <see href="https://spec.matrix.org/v1.11/client-server-api/#post_matrixclientv3login"/>
	/// </summary>
	[Post("/login")]
	public Task<LoginResponse> Login(LoginRequest request);

	/// <summary><see cref="Refresh"/></summary>
	public record RefreshRequest(string refresh_token);
	/// <summary><see cref="Refresh"/></summary>
	public record RefreshResponse(string access_token, int? expires_in_ms, string? refresh_token);

	/// <summary> Use a refresh token to reaquire a new access token </summary>
	[Post("/refresh")]
	public Task<RefreshResponse> Refresh(RefreshRequest request);

	/// <summary><see cref="GetJoinedRooms"/></summary>
	public record JoinedRoomsResponse(string[] joined_rooms);

	/// <summary> Get a list of IDs of currently joined rooms. </summary>
	[Get("/joined_rooms")]
	[Headers("Authorization: Bearer")]
	public Task<JoinedRoomsResponse> GetJoinedRooms();

	/// <summary>Represents a room event content</summary>
	public abstract record EventContent();

	[JsonPolymorphic(TypeDiscriminatorPropertyName = "msgtype")]
	[JsonDerivedType(typeof(TextMessage), typeDiscriminator: "m.text")]
	/// <summary> Represents any <c>m.room.message</c> event. </summary>
	public abstract record Message(string body) : EventContent();
	/// <summary> Represents a basic <c>msgtype: m.text</c> message. </summary>
	public record TextMessage(string body) : Message(body: body);

	/// <summary><see cref="SendEvent"/></summary>
	public record SendEventResponse(string event_id);

	/// <summary>Send a raw event to a room. Can be of any type.</summary>
	/// <returns> The <c>event_id</c> of the sent event </returns>
	/// <param name="body">See <see cref="EventContent"/></param>
	[Put("/rooms/{roomId}/send/{eventType}/{txnId}")]
	[Headers("Authorization: Bearer")]
	public Task<SendEventResponse> SendEvent<TEvent>(string roomId, string eventType, string txnId, TEvent body) where TEvent : EventContent;
}

