namespace matrix_dotnet;

using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using Refit;

/// <summary>
/// The IMatrixApi interface represents API endpoints directly and its implementation gets generated by Refit.
/// </summary>
public interface IMatrixApi {
	public record ErrorResponse(string errcode, string error, bool? soft_logout = null);

	[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
	[JsonDerivedType(typeof(UserIdentifier), typeDiscriminator: "m.id.user")]
	[JsonDerivedType(typeof(PhoneIdentifier), typeDiscriminator: "m.id.phone")]
	[JsonDerivedType(typeof(ThirdpartyIdentifier), typeDiscriminator: "m.id.thirdparty")]
	public abstract record Identifier();
	public record UserIdentifier(string user) : Identifier();
	public record PhoneIdentifier(string country, string phone) : Identifier();
	public record ThirdpartyIdentifier(string medium, string address) : Identifier();

	/// <summary>The return value of the <see cref="Login"/> function.</summary>
	public record LoginResponse(
		string access_token,
		string device_id,
		int? expires_in_ms,
		// string? HomeServer, // DEPRECATED
		string? refresh_token,
		// object WellKnown, // NOT IMPLEMENTED
		string user_id
	);

	/// <summary><see cref="Login"/></summary>
	[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
	[JsonDerivedType(typeof(PasswordLoginRequest), typeDiscriminator: "m.login.password")]
	[JsonDerivedType(typeof(TokenLoginRequest), typeDiscriminator: "m.login.token")]
	public abstract record LoginRequest(
		string? initial_device_display_name = null,
		string? device_id = null,
		bool refresh_token = true
	);

	/// <summary><see cref="Login"/></summary>
	public record PasswordLoginRequest(
			Identifier identifier,
			string password,
			string? initial_device_display_name = null,
			string? device_id = null,
			bool refresh_token = true
	) : LoginRequest(initial_device_display_name, device_id, refresh_token);

	/// <summary><see cref="Login"/></summary>
	public record TokenLoginRequest(
			string token,
			string? initial_device_display_name = null,
			string? device_id = null,
			bool refresh_token = true
	) : LoginRequest(initial_device_display_name, device_id, refresh_token);

	/// <summary> Perform login to receive an access and an optional refresh token.
	/// <see href="https://spec.matrix.org/v1.11/client-server-api/#post_matrixclientv3login"/>
	/// </summary>
	[Post("/login")]
	public Task<LoginResponse> Login(LoginRequest request);

	/// <summary><see cref="Refresh"/></summary>
	public record RefreshRequest(string refresh_token);
	/// <summary><see cref="Refresh"/></summary>
	public record RefreshResponse(string access_token, int? expires_in_ms, string? refresh_token);

	/// <summary> Use a refresh token to reaquire a new access token </summary>
	[Post("/refresh")]
	public Task<RefreshResponse> Refresh(RefreshRequest request);

	/// <summary><see cref="GetJoinedRooms"/></summary>
	public record JoinedRoomsResponse(string[] joined_rooms);

	/// <summary> Get a list of IDs of currently joined rooms. </summary>
	[Get("/joined_rooms")]
	[Headers("Authorization: Bearer")]
	public Task<JoinedRoomsResponse> GetJoinedRooms();

	/// <summary>Represents a room event content</summary>
	public abstract record EventContent() {

		public static EventContent FromJSON(string type, JsonObject obj) {
			EventContent? ec = type switch {
				"m.room.message" => JsonSerializer.Deserialize<Message>(obj),
				_ => throw new InvalidOperationException("Unknown event type")
			};
			if (ec is null) throw new Exception("Is borked");
			return ec;
		}
	};

	[JsonPolymorphic(TypeDiscriminatorPropertyName = "msgtype")]
	[JsonDerivedType(typeof(TextMessage), typeDiscriminator: "m.text")]
	/// <summary> Represents any <c>m.room.message</c> event. </summary>
	public abstract record Message(string body) : EventContent();
	/// <summary> Represents a basic <c>msgtype: m.text</c> message. </summary>
	public record TextMessage(string body) : Message(body: body);

	/// <summary><see cref="SendEvent"/></summary>
	public record SendEventResponse(string event_id);

	/// <summary>Send a raw event to a room. Can be of any type.</summary>
	/// <returns> The <c>event_id</c> of the sent event </returns>
	/// <param name="body">See <see cref="EventContent"/></param>
	[Put("/rooms/{roomId}/send/{eventType}/{txnId}")]
	[Headers("Authorization: Bearer")]
	public Task<SendEventResponse> SendEvent<TEvent>(string roomId, string eventType, string txnId, TEvent body) where TEvent : EventContent;

	public record Event(
		EventContent content,
		string type
	) {
		[JsonConstructor]
		public Event(JsonObject content, string type) : this(EventContent.FromJSON(type, content), type) {}
	};

	public record StrippedStateEvent(EventContent content, string type) : Event(content, type) {}
	public record ClientEventWithoutRoomID(EventContent content, string type) : Event(content, type) {}

/*	public record StrippedStateEvent(
		EventContent content,
		string sender,
		string state_key
	) : Event(content) {
		[JsonConstructor]
		public StrippedStateEvent(
				JsonObject content,
				string type,
				string sender,
				string state_key
		) : this(EventContent.FromJSON(type, content), sender, state_key) {}
	};

	public record ClientEventWithoutRoomID(
		EventContent content,
		string event_id,
		int origin_server_ts,
		string sender,
		string? state_key,
		UnsignedData? unsigned
	) : Event(content) {
		public ClientEventWithoutRoomID(
			JsonObject content,
			string type,
			string event_id,
			int origin_server_ts,
			string sender,
			string? state_key,
			UnsignedData? unsigned
		) : this(EventContent.FromJSON(type, content), event_id, origin_server_ts, sender, state_key, unsigned) {}
	}; */

	public record UnsignedData(
		int? age,
		string? membership,
		EventContent? prev_content,
		ClientEventWithoutRoomID? redacted_because,
		string? transaction_id
	);

	public record RoomSummary(
		string[] heroes,
		int invited_member_count,
		int joined_member_count
	) {
		[JsonPropertyName("m.heroes")] // Why??
		string[] heroes = heroes;
		[JsonPropertyName("m.invited_member_count")]
		int invited_member_count = invited_member_count;
		[JsonPropertyName("m.joined_member_count")]
		int joined_member_coun = joined_member_count;
	};

	public record UnreadNotificationCounts(
		int highlight_count,
		int notification_count
	);

	public record InvitedRoom(InviteState invite_state);
	public record JoinedRoom(
		AccountData account_data,
		Ephemeral ephemeral,
		State state,
		RoomSummary summary,
		Timeline timeline,
		UnreadNotificationCounts unread_notifications,
		Dictionary<string, UnreadNotificationCounts> unread_thread_notifications
	);
	public record KnockedRoom();
	public record LeftRoom();

	public record Rooms(
		Dictionary<string, InvitedRoom> invite,
		Dictionary<string, JoinedRoom> join,
		Dictionary<string, KnockedRoom> knock,
		Dictionary<string, LeftRoom> leave
	);

	public abstract record EventList<TEvent>(TEvent[] events) where TEvent : Event;
	public record AccountData(Event[] events) : EventList<Event>(events);
	public record Presence(Event[] events) : EventList<Event>(events);
	public record ToDevice(Event[] events) : EventList<Event>(events);
	public record Ephemeral(Event[] events) : EventList<Event>(events);
	public record InviteState(StrippedStateEvent[] events) : EventList<StrippedStateEvent>(events);
	public record State(ClientEventWithoutRoomID[] events) : EventList<ClientEventWithoutRoomID>(events);
	public record Timeline(
		ClientEventWithoutRoomID[] events,
		bool limited,
		string prev_batch
	) : EventList<ClientEventWithoutRoomID>(events);
	

	public record SyncResponse(
		AccountData account_data,
		// DeviceLists device_lists, // NOT IMPLEMENTED: E2EE
		// Dictionary<string, integer> device_one_time_keys_count, // NOT IMPLEMENTED: E2EE
		string next_batch,
		Presence? presence,
		Rooms? rooms,
		ToDevice? to_device
	);

	public enum SetPresence { offline, online, unavailable }

	/// <summary> Sync events. See <see href="https://spec.matrix.org/v1.11/client-server-api/#syncing"/></summary>
	[Get("/sync")]
	[Headers("Authorization: Bearer")]
	public Task<SyncResponse> Sync(
		string? filter = null,
		string full_state = "false", // TODO: false.ToString() == "False" and matrix doesn't like that
		SetPresence set_presence = SetPresence.offline,
		string? since = null,
		int timeout = 0
	);


}

